// Rule.cpp — pack parsing, rule compilation and matching.
//
// Every content rule, whatever its kind, becomes one RE2 pattern and they all
// go into a single RE2::Set. A scan is then two phases: ask the set which
// rules match anywhere in the buffer (one pass, no offsets), and only for
// those run the individual pattern to locate each hit. The common case in a
// forensic image is "none of them", and that costs exactly one pass.
//
// RE2 runs in Latin-1 so a byte is a byte: evidence is not text, and a UTF-8
// mode would refuse to look at most of a flash dump.
#include "omnitrace/rules/Rule.h"

#include <algorithm>
#include <array>
#include <cctype>
#include <cstring>
#include <fstream>
#include <sstream>

#include <re2/re2.h>
#include <re2/set.h>
#include <yaml-cpp/yaml.h>

#include "omnitrace/core/Text.h"

namespace omnitrace::rules {

// Embedded rules/*.yaml, generated by src/rules/cmake/embed_rules.cmake.
// Declared at namespace scope, not inside an anonymous namespace: a type with
// internal linkage cannot name a variable defined in another translation unit,
// which clang refuses and gcc quietly accepted.
namespace detail {
struct EmbeddedYaml {
    const char* name;
    const unsigned char* data;
    std::size_t size;
};
extern const EmbeddedYaml kEmbeddedRules[];
extern const std::size_t kEmbeddedRulesCount;
}  // namespace detail

namespace {

std::string hex_to_regex(std::string_view pattern, bool& ok) {
    std::string out;
    std::string digits;
    for (const char c : pattern) {
        if (std::isspace(static_cast<unsigned char>(c)) != 0) continue;
        digits.push_back(c);
    }
    ok = digits.size() % 2 == 0 && !digits.empty();
    if (!ok) return {};
    for (std::size_t i = 0; i + 1 < digits.size(); i += 2) {
        const std::string byte = digits.substr(i, 2);
        if (byte == "??" || byte == "**") {
            out += "(?s).";  // any byte, newline included
            continue;
        }
        const bool hex = std::isxdigit(static_cast<unsigned char>(byte[0])) != 0 &&
                         std::isxdigit(static_cast<unsigned char>(byte[1])) != 0;
        if (!hex) {
            ok = false;
            return {};
        }
        out += "\\x{" + byte + "}";
    }
    return out;
}

// A rule's pattern as RE2 sees it. Literal and hex are lowered to regex so one
// set covers every kind and a scan stays a single pass.
std::string to_regex(const Rule& r, bool& ok) {
    ok = true;
    switch (r.kind) {
        case Kind::Regex:
            return r.pattern;
        case Kind::Literal:
            return RE2::QuoteMeta(r.pattern);
        case Kind::Hex:
            return hex_to_regex(r.pattern, ok);
        case Kind::GlobPath:
            break;
    }
    ok = false;
    return {};
}

// Shell-style glob over a path, matched a path segment at a time. Splitting
// on '/' first is what makes this both correct and cheap: inside a segment
// there is no separator, so '*' and '?' are the classic two-pointer glob with
// no backtracking subtleties, and only '**' has to try several segment counts
// -- and a path is a handful of segments deep.
//
// Matching the whole string at once with one backtrack point, which is the
// usual shortcut, is wrong here: a '*' that stops at '/' can fail after a
// later '*' has already committed, and recovering needs to back up past it.
std::vector<std::string_view> split_path(std::string_view s) {
    std::vector<std::string_view> out;
    std::size_t start = 0;
    for (std::size_t i = 0; i <= s.size(); ++i) {
        if (i == s.size() || s[i] == '/') {
            out.push_back(s.substr(start, i - start));
            start = i + 1;
        }
    }
    return out;
}

// One segment: '*' matches any run of characters, '?' exactly one.
bool segment_match(std::string_view pat, std::string_view s) {
    std::size_t p = 0, t = 0, star = std::string_view::npos, star_t = 0;
    while (t < s.size()) {
        if (p < pat.size() && (pat[p] == '?' || pat[p] == s[t])) {
            ++p;
            ++t;
        } else if (p < pat.size() && pat[p] == '*') {
            star = p++;
            star_t = t;
        } else if (star != std::string_view::npos) {
            p = star + 1;
            t = ++star_t;
        } else {
            return false;
        }
    }
    while (p < pat.size() && pat[p] == '*') ++p;
    return p == pat.size();
}

bool glob_match(std::string_view pattern, std::string_view path) {
    const std::vector<std::string_view> pat = split_path(pattern);
    const std::vector<std::string_view> seg = split_path(path);
    // match[i][j]: pat[i..] matches seg[j..]. Bounded by the segment counts,
    // so a hostile pattern costs a table, not an exponential search.
    const std::size_t np = pat.size(), ns = seg.size();
    std::vector<std::uint8_t> table((np + 1) * (ns + 1), 0);
    const auto at = [&](std::size_t i, std::size_t j) -> std::uint8_t& {
        return table[i * (ns + 1) + j];
    };
    at(np, ns) = 1;
    for (std::size_t i = np; i-- > 0;) {
        for (std::size_t j = ns + 1; j-- > 0;) {
            if (pat[i] == "**") {
                // Zero segments, or one more and try again.
                at(i, j) = at(i + 1, j) != 0 || (j < ns && at(i, j + 1) != 0) ? 1 : 0;
            } else if (j < ns && segment_match(pat[i], seg[j])) {
                at(i, j) = at(i + 1, j + 1);
            }
        }
    }
    return at(0, 0) != 0;
}

// ------------------------------------------------------------ post-filters

bool vin_checksum(std::string_view v) {
    if (v.size() != 17) return false;
    static constexpr int kWeight[17] = {8, 7, 6, 5, 4, 3, 2, 10, 0, 9, 8, 7, 6, 5, 4, 3, 2};
    // The transliteration is not a formula: the letters restart at 1 twice and
    // skip I, O and Q. Spelled out rather than computed, because a clever
    // index into a gapped string is how this got the wrong answer first time.
    const auto value = [](char c) -> int {
        if (c >= '0' && c <= '9') return c - '0';
        switch (std::toupper(static_cast<unsigned char>(c))) {
            case 'A':
            case 'J':
                return 1;
            case 'B':
            case 'K':
            case 'S':
                return 2;
            case 'C':
            case 'L':
            case 'T':
                return 3;
            case 'D':
            case 'M':
            case 'U':
                return 4;
            case 'E':
            case 'N':
            case 'V':
                return 5;
            case 'F':
            case 'W':
                return 6;
            case 'G':
            case 'P':
            case 'X':
                return 7;
            case 'H':
            case 'Y':
                return 8;
            case 'R':
            case 'Z':
                return 9;
            default:
                return -1;  // I, O, Q are not used in a VIN
        }
    };
    int sum = 0;
    for (std::size_t i = 0; i < 17; ++i) {
        const int n = value(v[i]);
        if (n < 0) return false;
        sum += n * kWeight[i];
    }
    const int check = sum % 11;
    const char expect = check == 10 ? 'X' : static_cast<char>('0' + check);
    if (std::toupper(static_cast<unsigned char>(v[8])) != expect) return false;

    // The check digit is one in eleven, so a placeholder can pass it by
    // chance: `X1X2X3X4X6X7X8X9X`, which sits in ICU's data tables and in
    // iconv, computes to X and is not a vehicle. A VIN is a manufacturer
    // prefix, a descriptor and a serial, and no real one is more than half
    // the same character -- the most repeated character in a genuine VIN is
    // typically seen three times.
    std::array<int, 256> seen{};
    for (const char c : v)
        ++seen[static_cast<unsigned char>(std::toupper(static_cast<unsigned char>(c)))];
    return *std::max_element(seen.begin(), seen.end()) * 2 <= static_cast<int>(v.size());
}

bool luhn(std::string_view v) {
    int sum = 0;
    int digits = 0;
    bool dbl = false;
    char first = 0;
    bool uniform = true;
    for (auto it = v.rbegin(); it != v.rend(); ++it) {
        if (std::isdigit(static_cast<unsigned char>(*it)) == 0) continue;
        if (first == 0) first = *it;
        uniform = uniform && *it == first;
        int d = *it - '0';
        if (dbl && (d *= 2) > 9) d -= 9;
        sum += d;
        dbl = !dbl;
        ++digits;
    }
    // A run of one repeated digit passes the checksum (fifteen zeros sum to
    // zero) and is a filler field in every device that has one, not an IMEI.
    return digits >= 12 && !uniform && sum % 10 == 0;
}

// A MAC of all-zero or all-ff is a placeholder, not a device.
bool mac_is_real(std::string_view v) {
    int zero = 0, ff = 0, octets = 0;
    for (std::size_t i = 0; i + 1 < v.size(); ++i) {
        if (std::isxdigit(static_cast<unsigned char>(v[i])) == 0) continue;
        if (std::isxdigit(static_cast<unsigned char>(v[i + 1])) == 0) continue;
        const std::string oct = std::string(v.substr(i, 2));
        ++octets;
        if (oct == "00") ++zero;
        if (oct == "ff" || oct == "FF" || oct == "Ff" || oct == "fF") ++ff;
        ++i;
    }
    return octets == 6 && zero != 6 && ff != 6;
}

bool passes(const std::string& filter, std::string_view match) {
    if (filter.empty()) return true;
    if (filter == "vin-checksum") return vin_checksum(match);
    if (filter == "luhn") return luhn(match);
    if (filter == "mac-not-broadcast") return mac_is_real(match);
    return true;  // an unknown filter was rejected at build time
}

bool known_filter(const std::string& f) {
    return f.empty() || f == "vin-checksum" || f == "luhn" || f == "mac-not-broadcast";
}

// Bytes as an examiner can read them in a YAML file: printable ASCII kept,
// everything else as \xNN, and capped so one hit cannot carry a megabyte.
std::string quote_bytes(std::span<const std::uint8_t> b, std::size_t cap) {
    std::string out;
    out.reserve(std::min(b.size(), cap) + 8);
    std::size_t used = 0;
    for (const std::uint8_t c : b) {
        if (used >= cap) {
            out += "...";
            break;
        }
        if (c >= 0x20 && c < 0x7F) {
            if (c == '\\') out += '\\';
            out.push_back(static_cast<char>(c));
            ++used;
        } else if (c == '\n' || c == '\r' || c == '\t') {
            out += c == '\n' ? "\\n" : (c == '\r' ? "\\r" : "\\t");
            used += 2;
        } else {
            static const char* kHex = "0123456789abcdef";
            out += "\\x";
            out.push_back(kHex[c >> 4]);
            out.push_back(kHex[c & 0xF]);
            used += 4;
        }
    }
    return out;
}

std::string node_str(const YAML::Node& n, const char* key, const std::string& fallback = {}) {
    const YAML::Node v = n[key];
    return v && v.IsScalar() ? v.as<std::string>() : fallback;
}

}  // namespace

const char* kind_name(Kind k) {
    switch (k) {
        case Kind::Regex:
            return "regex";
        case Kind::Literal:
            return "literal";
        case Kind::Hex:
            return "hex";
        case Kind::GlobPath:
            return "glob-path";
    }
    return "regex";
}

const char* severity_name(Severity s) {
    switch (s) {
        case Severity::Info:
            return "info";
        case Severity::Low:
            return "low";
        case Severity::Medium:
            return "medium";
        case Severity::High:
            return "high";
        case Severity::Critical:
            return "critical";
    }
    return "medium";
}

bool parse_kind(std::string_view s, Kind& out) {
    if (s == "regex") return out = Kind::Regex, true;
    if (s == "literal") return out = Kind::Literal, true;
    if (s == "hex") return out = Kind::Hex, true;
    if (s == "glob-path") return out = Kind::GlobPath, true;
    return false;
}

bool parse_severity(std::string_view s, Severity& out) {
    if (s == "info") return out = Severity::Info, true;
    if (s == "low") return out = Severity::Low, true;
    if (s == "medium") return out = Severity::Medium, true;
    if (s == "high") return out = Severity::High, true;
    if (s == "critical") return out = Severity::Critical, true;
    return false;
}

Status RulePack::parse(std::string_view yaml, std::string_view origin, RulePack& out) {
    out = RulePack{};
    out.origin = std::string(origin);
    YAML::Node doc;
    try {
        doc = YAML::Load(std::string(yaml));
    } catch (const std::exception& e) {
        return Status::fail("rules-bad-yaml: " + std::string(origin) + ": " + e.what());
    }
    if (!doc.IsMap()) return Status::fail("rules-bad-yaml: " + std::string(origin) + ": not a map");

    out.name = node_str(doc, "pack");
    if (out.name.empty())
        return Status::fail("rules-no-name: " + std::string(origin) + ": 'pack' is required");
    if (const YAML::Node v = doc["version"]; v && v.IsScalar()) {
        try {
            out.version = v.as<std::uint32_t>();
        } catch (const std::exception&) {
            return Status::fail("rules-bad-version: " + out.name + ": 'version' is not a number");
        }
    }
    const YAML::Node list = doc["rules"];
    if (!list || !list.IsSequence())
        return Status::fail("rules-no-rules: " + out.name + ": 'rules' must be a sequence");

    std::map<std::string, std::size_t> seen;
    for (std::size_t i = 0; i < list.size(); ++i) {
        const YAML::Node n = list[i];
        const std::string where = out.name + ": rule[" + std::to_string(i) + "]";
        if (!n.IsMap()) return Status::fail("rules-bad-rule: " + where + " is not a map");

        Rule r;
        r.pack = out.name;
        r.id = node_str(n, "id");
        if (r.id.empty()) return Status::fail("rules-no-id: " + where + ": 'id' is required");
        if (!seen.emplace(r.id, i).second)
            return Status::fail("rules-duplicate-id: " + out.name + ": '" + r.id +
                                "' is defined twice");
        r.category = node_str(n, "category", "other");
        r.description = node_str(n, "description");
        r.pattern = node_str(n, "pattern");
        if (r.pattern.empty())
            return Status::fail("rules-no-pattern: " + out.name + ": '" + r.id +
                                "': 'pattern' is required");
        const std::string kind = node_str(n, "kind", "regex");
        if (!parse_kind(kind, r.kind))
            return Status::fail("rules-bad-kind: " + out.name + ": '" + r.id + "': '" + kind +
                                "' is not regex, literal, hex or glob-path");
        const std::string sev = node_str(n, "severity", "medium");
        if (!parse_severity(sev, r.severity))
            return Status::fail("rules-bad-severity: " + out.name + ": '" + r.id + "': '" + sev +
                                "' is not info, low, medium, high or critical");
        r.validate = node_str(n, "validate");
        if (!known_filter(r.validate))
            return Status::fail("rules-bad-validate: " + out.name + ": '" + r.id + "': '" +
                                r.validate +
                                "' is not a built-in filter (vin-checksum, luhn, "
                                "mac-not-broadcast)");
        if (const YAML::Node sc = n["scope"]; sc && sc.IsSequence()) {
            r.in_files = r.in_regions = false;
            for (const YAML::Node& s : sc) {
                const std::string v = s.as<std::string>();
                if (v == "files")
                    r.in_files = true;
                else if (v == "regions")
                    r.in_regions = true;
                else
                    return Status::fail("rules-bad-scope: " + out.name + ": '" + r.id + "': '" + v +
                                        "' is not files or regions");
            }
            if (!r.in_files && !r.in_regions)
                return Status::fail("rules-empty-scope: " + out.name + ": '" + r.id +
                                    "': 'scope' lists nothing");
        }
        out.rules.push_back(std::move(r));
    }
    if (out.rules.empty())
        return Status::fail("rules-no-rules: " + out.name + ": the pack defines no rules");
    return Status::success();
}

Status RulePack::load_file(const std::string& path, RulePack& out) {
    std::ifstream f(path, std::ios::binary);
    if (!f) return Status::fail("rules-unreadable: cannot open '" + path + "'");
    std::ostringstream ss;
    ss << f.rdbuf();
    return parse(ss.str(), path, out);
}

const std::vector<RulePack>& RulePack::builtin() {
    static const std::vector<RulePack> packs = [] {
        std::vector<RulePack> v;
        for (std::size_t i = 0; i < detail::kEmbeddedRulesCount; ++i) {
            const auto& e = detail::kEmbeddedRules[i];
            RulePack p;
            const std::string_view text(reinterpret_cast<const char*>(e.data), e.size);
            if (RulePack::parse(text, e.name, p)) v.push_back(std::move(p));
        }
        return v;
    }();
    return packs;
}

// ------------------------------------------------------------------- Engine

struct Engine::Impl {
    struct Compiled {
        Rule rule;
        std::unique_ptr<RE2> re;  // for locating, once the set says it matched
    };
    std::vector<Compiled> content;
    std::vector<Rule> paths;
    std::unique_ptr<RE2::Set> set;
};

Engine::Engine() : impl_(std::make_unique<Impl>()) {}
Engine::~Engine() = default;
Engine::Engine(Engine&&) noexcept = default;
Engine& Engine::operator=(Engine&&) noexcept = default;

Status Engine::build(const std::vector<RulePack>& packs, Engine& out) {
    out.impl_ = std::make_unique<Impl>();
    Impl& d = *out.impl_;

    RE2::Options opts;
    opts.set_encoding(RE2::Options::EncodingLatin1);  // a byte is a byte
    opts.set_log_errors(false);
    opts.set_max_mem(64 << 20);
    opts.set_never_capture(true);

    d.set = std::make_unique<RE2::Set>(opts, RE2::UNANCHORED);
    for (const RulePack& p : packs) {
        for (const Rule& r : p.rules) {
            if (r.kind == Kind::GlobPath) {
                d.paths.push_back(r);
                continue;
            }
            bool ok = true;
            const std::string pattern = to_regex(r, ok);
            if (!ok)
                return Status::fail("rules-bad-pattern: " + p.name + ": '" + r.id +
                                    "': not a valid " + kind_name(r.kind) + " pattern");
            std::string err;
            if (d.set->Add(pattern, &err) < 0)
                return Status::fail("rules-bad-pattern: " + p.name + ": '" + r.id + "': " + err);
            auto re = std::make_unique<RE2>(pattern, opts);
            if (!re->ok())
                return Status::fail("rules-bad-pattern: " + p.name + ": '" + r.id +
                                    "': " + re->error());
            d.content.push_back(Impl::Compiled{r, std::move(re)});
        }
    }
    if (!d.set->Compile())
        return Status::fail("rules-set-too-large: the combined patterns exceed RE2's memory bound");
    return Status::success();
}

std::size_t Engine::content_rules() const {
    return impl_ ? impl_->content.size() : 0;
}

std::size_t Engine::path_rules() const {
    return impl_ ? impl_->paths.size() : 0;
}

void Engine::scan_bytes(std::span<const std::uint8_t> data, bool in_files, const ScanLimits& lim,
                        std::vector<Hit>& out) const {
    if (!impl_ || impl_->content.empty() || data.empty()) return;
    const Impl& d = *impl_;
    const std::size_t n =
        static_cast<std::size_t>(std::min<std::uint64_t>(data.size(), lim.max_bytes_per_item));
    const re2::StringPiece subject(reinterpret_cast<const char*>(data.data()), n);

    // Phase one: which rules match anywhere at all. Usually none, and that is
    // one pass over the buffer rather than one pass per rule.
    std::vector<int> matched;
    if (!d.set->Match(subject, &matched)) return;

    const std::size_t before = out.size();
    for (const int idx : matched) {
        if (idx < 0 || static_cast<std::size_t>(idx) >= d.content.size()) continue;
        const Impl::Compiled& c = d.content[static_cast<std::size_t>(idx)];
        if (in_files ? !c.rule.in_files : !c.rule.in_regions) continue;

        // Phase two: locate this rule's matches.
        std::uint64_t kept = 0;
        re2::StringPiece rest = subject;
        while (kept < lim.max_hits_per_rule_per_item && !rest.empty()) {
            re2::StringPiece m;
            if (!c.re->Match(subject, static_cast<std::size_t>(rest.data() - subject.data()),
                             subject.size(), RE2::UNANCHORED, &m, 1))
                break;
            const std::size_t at = static_cast<std::size_t>(m.data() - subject.data());
            const std::string_view text(m.data(), m.size());
            if (passes(c.rule.validate, text)) {
                Hit h;
                h.rule = c.rule.id;
                h.pack = c.rule.pack;
                h.category = c.rule.category;
                h.severity = c.rule.severity;
                h.offset = at;
                h.match =
                    quote_bytes(std::span<const std::uint8_t>(data.data() + at, m.size()), 160);
                const std::size_t ctx_from = at > lim.context_bytes ? at - lim.context_bytes : 0;
                const std::size_t ctx_to = std::min(n, at + m.size() + lim.context_bytes);
                h.context = quote_bytes(
                    std::span<const std::uint8_t>(data.data() + ctx_from, ctx_to - ctx_from), 400);
                out.push_back(std::move(h));
                ++kept;
            }
            // Always move on by at least one byte: an empty match would spin.
            const std::size_t next = at + std::max<std::size_t>(m.size(), 1);
            if (next >= n) break;
            rest = re2::StringPiece(subject.data() + next, n - next);
        }
    }
    // Deterministic order, so a manifest is byte-identical run to run.
    std::sort(out.begin() + static_cast<std::ptrdiff_t>(before), out.end(),
              [](const Hit& a, const Hit& b) {
                  if (a.offset != b.offset) return a.offset < b.offset;
                  if (a.pack != b.pack) return a.pack < b.pack;
                  return a.rule < b.rule;
              });
}

void Engine::scan_path(const std::string& path, std::vector<Hit>& out) const {
    if (!impl_) return;
    for (const Rule& r : impl_->paths) {
        if (!glob_match(r.pattern, path)) continue;
        Hit h;
        h.rule = r.id;
        h.pack = r.pack;
        h.category = r.category;
        h.severity = r.severity;
        h.offset = 0;
        h.match = sanitize_utf8(path);
        out.push_back(std::move(h));
    }
    std::sort(out.begin(), out.end(), [](const Hit& a, const Hit& b) {
        if (a.pack != b.pack) return a.pack < b.pack;
        return a.rule < b.rule;
    });
}

}  // namespace omnitrace::rules
