# embed_rules.cmake — cmake -DOUTPUT=<cpp> -DINPUTS=<a.yaml;b.yaml> -P this
#
# Writes one C++ translation unit holding every input file as a byte array,
# exposed to Rule.cpp through omnitrace::rules::detail::kEmbeddedRules.
# Bytes are emitted as hex so the YAML text needs no escaping and the result is
# byte-identical to the source file (no newline translation, no raw-string
# delimiter clashes).
if(NOT OUTPUT)
  message(FATAL_ERROR "embed_rules.cmake: OUTPUT not set")
endif()
set(_body "// Generated by src/discovery/cmake/embed_rules.cmake. Do not edit.\n")
string(APPEND _body "#include <cstddef>\n\nnamespace omnitrace::rules::detail {\n\n")
string(APPEND _body "struct EmbeddedYaml {\n    const char* name;\n    const unsigned char* data;\n    std::size_t size;\n};\n\n")
set(_index 0)
set(_table "")
foreach(_file IN LISTS INPUTS)
  get_filename_component(_name "${_file}" NAME)
  file(READ "${_file}" _hex HEX)
  string(LENGTH "${_hex}" _hexlen)
  math(EXPR _size "${_hexlen} / 2")
  # "0x61,0x62,..." — one entry per byte, wrapped every 32 bytes for readability.
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
  string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n    " _bytes "${_bytes}")
  string(APPEND _body "// ${_name} (${_size} bytes)\nstatic const unsigned char kFile${_index}[] = {\n    ${_bytes}\n    0x00};\n\n")
  string(APPEND _table "    {\"${_name}\", kFile${_index}, ${_size}},\n")
  math(EXPR _index "${_index} + 1")
endforeach()
string(APPEND _body "extern const EmbeddedYaml kEmbeddedRules[];\nextern const std::size_t kEmbeddedRulesCount;\n\n")
if(_index EQUAL 0)
  string(APPEND _body "const EmbeddedYaml kEmbeddedRules[] = {{\"\", nullptr, 0}};\nconst std::size_t kEmbeddedRulesCount = 0;\n")
else()
  string(APPEND _body "const EmbeddedYaml kEmbeddedRules[] = {\n${_table}};\nconst std::size_t kEmbeddedRulesCount = ${_index};\n")
endif()
string(APPEND _body "\n}  // namespace omnitrace::rules::detail\n")
get_filename_component(_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_dir}")
# Only touch the output when it changed so incremental builds stay incremental.
set(_old "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" _old)
endif()
if(NOT _old STREQUAL _body)
  file(WRITE "${OUTPUT}" "${_body}")
endif()
