# WriteGitSha.cmake — run at *build* time to record which commit produced the
# binary. See cmake/GitSha.cmake for why build time rather than configure time.
#
# Expects: OUT (header to write), SRC (source dir), OVERRIDE (optional).
# Writes OUT only when the value changes, so nothing rebuilds needlessly.

set(_sha "")
if(OVERRIDE)
  # A build from a source archive has no .git; the packager passes the sha it
  # built from (-DOMNITRACE_GIT_SHA=...), which is how the container gets one.
  set(_sha "${OVERRIDE}")
else()
  find_package(Git QUIET)
  if(GIT_FOUND)
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" rev-parse --short=12 HEAD
      OUTPUT_VARIABLE _sha OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET RESULT_VARIABLE _rc)
    if(NOT _rc EQUAL 0)
      set(_sha "")
    else()
      # A case produced by a modified build has to say so: the commit alone
      # would name bytes that were never compiled.
      execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SRC}" status --porcelain --untracked-files=no
        OUTPUT_VARIABLE _dirty OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
      if(NOT _dirty STREQUAL "")
        set(_sha "${_sha}-dirty")
      endif()
    endif()
  endif()
endif()

set(_new "// Generated by cmake/WriteGitSha.cmake. Do not edit.\n#pragma once\n#define OMNITRACE_GIT_SHA \"${_sha}\"\n")
set(_old "")
if(EXISTS "${OUT}")
  file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _new)
  file(WRITE "${OUT}" "${_new}")
endif()
